version = 1
service = "codex-mcp"

[mcp_servers.atlassian]
ATLASSIAN_MCP_TOKEN = false

[mcp_servers.cloudflare-api]
CLOUDFLARE_API_TOKEN = true

#[mcp_servers.context7]
#CONTEXT7_API_KEY = true

[mcp_servers.figma]
FIGMA_OAUTH_TOKEN = false

[mcp_servers.huggingface]
HUGGINGFACE_TOKEN = true

[mcp_servers.jina-ai]
JINA_API_KEY = true

[mcp_servers.linear]
LINEAR_API_KEY = false

[mcp_servers.render]
RENDER_API_KEY = false

[mcp_servers.stripe]
STRIPE_API_KEY = false

[mcp_servers.vercel]
VERCEL_API_TOKEN = true
