[global_variables]
CODEX_HOME            = "/data/codex/usr/home"
CODEX_AGENTS          = "/data/codex/usr/agents"
CODEX_SKILLS          = "/data/codex/usr/skills"
CODEX_LOG_DIR         = "/data/codex/log"
CODEX_SQLITE_HOME     = "/data/codex/sqlite"
