@@define DBDIR /var/lib/aide
@@define LOGDIR /var/log/aide

database=file:@@{DBDIR}/aide.db
database_out=file:@@{DBDIR}/aide.db.new
gzip_dbout=yes

report_url=file:@@{LOGDIR}/aide.log

# Rules
PERMS = p+i+n+u+g+s+m+c+md5

# Monitor critical paths
/etc PERMS
/usr/bin PERMS
/usr/sbin PERMS
/boot PERMS

# Exclusions
/var/log.*  # volatile logs
/tmp.*      # temporary files
