# runtime features
[features]
# sandbox
guardian_approval = false
tool_call_mcp_elicitation = true
elevated_windows_sandbox = false
default_mode_request_user_input = true
# deprecated, replaced by exec_permission_approval. request_permissions = true
request_permissions_tool = true
request_rule = false
exec_permission_approvals = false
use_linux_sandbox_bwrap = true
use_legacy_landlock = false

# behavior
collaboration_modes = true
enable_fanout = false
fast_mode = false
code_mode = false
code_mode_only = false
memories = true
personality = true
child_agents_md = true
multi_agent = false
multi_agent_v2 = true
# deprecated, replaced by fanout. spawn_csv = false
remote_models = true

# tools
#collab = true
# deprecated, replaced by memories. memory_tool = true
tool_suggest = true
artifact = true
plugins = true
codex_hooks = true
powershell_utf8 = false
undo = true
sqlite = true
apply_patch_freeform = true
unified_exec = true
apps = true
apps_mcp_gateway = true
skill_env_var_dependency_prompt = false
skill_mcp_dependency_install = true
image_detail_original = false
image_generation = false

# shell
shell_tool = true
shell_snapshot = true
shell_zsh_fork = false

# git
codex_git_commit = false
js_repl = false
js_repl_tools_only = false

# device
tui_app_server = false
realtime_conversation_v2 = false
realtime_conversation = false
voice_transcription = false
runtime_metrics = false
enable_request_compression = true
responses_websockets_v2 = true
prevent_idle_sleep = false
